name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: "JDK ${{ matrix.java }}"
    strategy:
      matrix:
        java: [ 17, 24 ]
    runs-on: ubuntu-latest
    steps:
      # Cancel any previous runs for the same branch that are still running.
      - name: 'Cancel previous runs'
        uses: styfle/cancel-workflow-action@b173b6ec0100793626c2d9e6b90435061f4fc3e5
        with:
          access_token: ${{ github.token }}
      - name: 'Check out repository'
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
      - name: 'Set up JDK ${{ matrix.java }}'
        uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'
      - name: 'Install'
        shell: bash
        run: mvn -B install -U -DskipTests=true
      - name: 'Test'
        shell: bash
        run: mvn -B verify -U -Dmaven.javadoc.skip=true

  publish_snapshot:
    name: 'Publish snapshot'
    needs: test
    if: github.event_name == 'push' && github.repository == 'google/guava-beta-checker'
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
      - name: 'Set up JDK 17'
        uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'
          server-id: sonatype-nexus-snapshots
          server-username: CI_DEPLOY_USERNAME
          server-password: CI_DEPLOY_PASSWORD
      - name: 'Publish'
        env:
          CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
          CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
        run: mvn -B clean source:jar javadoc:jar deploy -DskipTests=true
